tooth/blog/urls.py
from django.conf.urls import *
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.views.generic import ListView, DetailView
from . import views, feed, models

info_dict = {
    'queryset' : models.Post.objects.published(),
    'date_field' : 'pub_date',
}

urlpatterns = [
	url(r'^/(?P<pub_date__year>\d{4})/(?P<pub_date__month>\d{1,2})/(?P<slug>[a-zA-Z0-9-]+)/?',
		views.PostDetail.as_view(), name="post_detail"),
	url(r'^/new/', views.post_new, name='post_new'),
	url(r'^/category/(?P<slug>[a-zA-Z0-9-]+)/?$', views.CategoryView.as_view(), name="category"),
    url(r'^/tag/(?P<slug>[a-zA-Z0-9-]+)/?$', views.TagView.as_view(), name="tag"),
	url(r'^', views.BlogIndex.as_view(), name="blog"),
	]

tooth/shop/urls.py
from django.conf.urls import *
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET, require_POST
from . import views, models

urlpatterns = [
	url(r'^/category/(?P<slug>[a-zA-Z0-9-]+)/?$', views.CategoryView.as_view(), name="shop_category"),
    url(r'^/tag/(?P<slug>[a-zA-Z0-9-]+)/?$', views.TagView.as_view(), name="shop_tag"),
	url(r'^/product/(?P<slug>[a-zA-Z0-9-]+)/?$', views.ProductDetailView.as_view(), name='shop_detail'),
	url(r'^/new_purchase/$', views.PurchaseFormView.as_view(), name='new_purchase'),
	url(r'^/purchase_list/$', views.PurchaseListView.as_view(), name='purchase_list'),
	url(r'^/purchase/(?P<pk>[0-9]+)/?', views.PurchaseDetailView.as_view(), name='purchase_details'),
	url(r'^/office/purchase_list/$', views.PurchaseOfficeListView.as_view(), name="office_purchase_list"),
	url(r'^/office/purchase/update/(?P<pk>[0-9]+)/?', views.PurchaseStatusUpdate.as_view(), name='office_purchase_status_update'),
	url(r'^$', views.ShopIndexView.as_view(), name='shop_index'),
	]

tooth/tooth/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from main_page import urls
from shop import urls
from blog import urls


urlpatterns = [
    url(r'^admin', include(admin.site.urls)),
    url('^markdown/', include( 'django_markdown.urls')),
    url(r'^blog', include('blog.urls', namespace='blog')),
    url(r'^shop', include('shop.urls', namespace='shop')),
    url(r'^email_marketing', include('email_marketing.urls', namespace='email_marketing')),
    url(r'^', include('main_page.urls', namespace="main_page")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.conf.urls import handler400, handler403, handler404, handler500

handler400 = 'main_page.views.handler400'
handler403 = 'main_page.views.handler403'
handler404 = 'main_page.views.handler404'
handler500 = 'main_page.views.handler500'

tooth/shop/models.py
from django.db import models
from datetime import datetime
from django.utils.text import slugify
from django.contrib.auth.models import User, Group
import main_page


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/shop/category/{0}/".format(self.slug)

    class Meta:
        verbose_name = "Shop Product Category"
        verbose_name_plural = 'Shop Product Categories'


class Tag(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    slug = models.SlugField(max_length=50, unique=True, blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/shop/tag/{0}/".format(self.slug)

    class Meta:
        verbose_name = "Shop Product Tag"
        verbose_name_plural = 'Shop Product Tags'

class Product(models.Model):
    name = models.CharField(max_length=300)
    slug = models.SlugField(max_length=150)
    description = models.TextField()
    photo = models.ImageField(upload_to='product_photo', blank=True, help_text="rozmiar - 400x300")
    manufacturer = models.CharField(max_length=100, blank=True)
    price_in_PLN = models.DecimalField(max_digits=6, decimal_places=2)
    retail = models.BooleanField(default=True, help_text="Do sprzedaży detalicznej = True, Do sprzedaży hurtowej - False")
    category = models.ForeignKey(Category, blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return "'" + self.name + "'" + " firmy: " + self.manufacturer + " cena: " + str(self.price_in_PLN) + " PLN"

    def get_absolute_url(self):
        return "/shop/product/{0}/".format(self.slug)

    class Meta:
        verbose_name = "Shop Product"
        verbose_name_plural = 'Shop Products'

class Purchase(models.Model):
    STATUSES = [
        ("A", "zamówione"),
        ("B", "opłacone"),
        ("C", "zwrócone"),
        ("D", "reklamacja"),
        ("E", "potwierdzone"),
        ("F", "wysłane"),
        ("G", "gotowe do odbioru"),
        ("H", "odebrane"),
        ("I", "nieopłacone"),
        ("J", "nieodebrane"),
        ("K", "zarchiwizowane"),
    ]
    product_1 = models.ForeignKey(Product, null=True, blank=True, related_name='product_slot_1')
    quantity_1 = models.PositiveIntegerField(null=True, blank=True, default=1)
    product_2 = models.ForeignKey(Product, null=True, blank=True, related_name='product_slot_2')
    quantity_2 = models.PositiveIntegerField(null=True, blank=True, default=1)
    product_3 = models.ForeignKey(Product, null=True, blank=True, related_name='product_slot_3')
    quantity_3 = models.PositiveIntegerField(null=True, blank=True, default=1)
    product_4 = models.ForeignKey(Product, null=True, blank=True, related_name='product_slot_4')
    quantity_4 = models.PositiveIntegerField(null=True, blank=True, default=1)
    product_5 = models.ForeignKey(Product, null=True, blank=True, related_name='product_slot_5')
    quantity_5 = models.PositiveIntegerField(null=True, blank=True, default=1)
    purchaser = models.ForeignKey(User)
    office = models.ForeignKey(main_page.models.Office, null=False, blank=False)
    date = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    status = models.CharField(choices=STATUSES, null=True, blank=True, max_length=20)
    additional_info = models.CharField(max_length=250, null=True, blank=True)
    purchase_id = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.purchaser.username + " " + str(self.date)

    def status_verbose(self):
        return dict(Purchase.STATUSES)[self.status]

    def get_absolute_url(self):
        return "/shop/purchase/{0}/".format(self.pk)

    def get_edit_url(self):
        return "/shop/office/purchase/update/{0}/".format(self.pk)

    def calculate_total_price(self):
        total_price = 0
        list_of_products = [
            (self.product_1, self.quantity_1),
            (self.product_2, self.quantity_2),
            (self.product_3, self.quantity_3),
            (self.product_4, self.quantity_4),
            (self.product_5, self.quantity_5),
            ]
        for product in list_of_products:
            if product[0]:
                total_price += product[0].price_in_PLN * product[1]
        return total_price

    def save(self, *args, **kwargs):
        if self.total_price is None:
            self.date = datetime.now()
            self.total_price = self.calculate_total_price()
            self.status = "A"
            purchase_id_text = '{} {}'.format(str(self.total_price), str(self.date))
            self.purchase_id = slugify(purchase_id_text)
        super(Purchase, self).save()

    class Meta:
        verbose_name = "Shop Purchase"
        verbose_name_plural = 'Shop Purchases'

tooth/shop/forms.py
from django import forms
from . import models

class PurchaseForm(forms.ModelForm):
    class Meta:
        model = models.Purchase
        exclude = ['status', 'total_price', 'purchase_id']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(PurchaseForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['purchaser'].queryset = models.User.objects.filter(id=user.id)
            self.fields['purchaser'].initial = models.User.objects.get(id=user.id)
            

class PurchaseStatusChangeForm(forms.ModelForm):
	class Meta:
		model = models.Purchase
		fields = ['status']
		

tooth/shop/views.py
from django.shortcuts import render
from django.views import generic
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.db.models import Q
from . import models, forms


class PurchaseFormView(generic.CreateView):
    model = models.Purchase
    form_class = forms.PurchaseForm
    template_name = 'shop/new_purchase.html'

    def get_success_url(self):
        return reverse('shop:purchase_list')

    def get_form_kwargs(self):
        kwargs = super(PurchaseFormView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.groups.filter(name='Patients').count() == 1, login_url='/forbidden'))
    def dispatch(self, *args, **kwargs):
        return super(PurchaseFormView, self).dispatch(*args, **kwargs)

class PurchaseStatusUpdate(generic.UpdateView):
    model = models.Purchase
    form_class = forms.PurchaseStatusChangeForm
    template_name = 'shop/purchase_status_edit.html'

    def get_success_url(self):
        return reverse('shop:office_purchase_list')

    def get_context_data(self, **kwargs):
        purchase = self.get_object().pk
        context = super(PurchaseStatusUpdate, self).get_context_data(**kwargs)
        context['purchase_list'] = models.Purchase.objects.filter(id=purchase).order_by('date')
        return context

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.groups.filter(name='Offices').count() == 1, login_url='/forbidden'))
    def dispatch(self, *args, **kwargs):
        return super(PurchaseStatusUpdate, self).dispatch(*args, **kwargs)


class PurchaseListView(generic.ListView):
    queryset = models.Purchase.objects.all()
    template_name = "shop/purchase_list.html"
    paginate_by = 12

    def get_queryset(self):
        queryset = super(PurchaseListView, self).get_queryset().filter(purchaser=self.request.user)
        return queryset

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.groups.filter(name='Patients').count() == 1, login_url='/forbidden'))
    def dispatch(self, *args, **kwargs):
        return super(PurchaseListView, self).dispatch(*args, **kwargs)


class PurchaseOfficeListView(generic.ListView):
    queryset = models.Purchase.objects.all().order_by('date') 
    template_name = "shop/purchase_list.html"
    paginate_by = 12

    def get_queryset(self):
        object_list = super(PurchaseOfficeListView, self).get_queryset()
        object_list = object_list.filter(office__user=self.request.user)
        return object_list.filter(status__in=["C","D","E","F","G","H","J"]).order_by('date')

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.groups.filter(name='Offices').count() == 1, login_url='/forbidden'))
    def dispatch(self, *args, **kwargs):
        return super(PurchaseOfficeListView, self).dispatch(*args, **kwargs)


class PurchaseDetailView(generic.DetailView):
    model = models.Purchase
    template_name = 'shop/purchase_detail.html'

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.groups.filter(name='Offices').count() == 1 or u.groups.filter(name='Patients').count() == 1, login_url='/forbidden'))
    def dispatch(self, *args, **kwargs):
        return super(PurchaseDetailView, self).dispatch(*args, **kwargs)


class ShopIndexView(generic.ListView):
	queryset = models.Product.objects.all()
	template_name = "shop/products_list.html"
	paginate_by = 12

class ProductDetailView(generic.DetailView):
    model = models.Product
    template_name = 'shop/product_detail.html'

class CategoryView(generic.ListView):
    model = models.Category
    paginate_by = 12
    template_name = 'shop/product_category.html'

    def get_queryset(self):
        slug = self.kwargs['slug']
        try:
            category = models.Category.objects.get(slug=slug)
            return models.Product.objects.filter(category=category)
        except models.Category.DoesNotExist:
            return models.Product.objects.none()

    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        slug = self.kwargs['slug']
        try:
            context['category'] = models.Category.objects.get(slug=slug)
        except models.Category.DoesNotExist:
            context['category'] = None
        return context

class TagView(generic.ListView):
    model = models.Tag
    paginate_by = 12
    template_name = 'shop/product_tag.html'

    def get_queryset(self):
        slug = self.kwargs['slug']
        try:
            tag = models.Tag.objects.get(slug=slug)
            return tag.product_set.all()
        except models.Tag.DoesNotExist:
            return models.Product.objects.none()

    def get_context_data(self, **kwargs):
        context = super(TagView, self).get_context_data(**kwargs)
        slug = self.kwargs['slug']
        try:
            context['tag'] = models.Tag.objects.get(slug=slug)
        except models.Tag.DoesNotExist:
            context['tag'] = None
        return context

tooth/shop/templates/shop/new_purchase.html
{% extends "base.html" %}

    {% load django_markdown %}
    {% load  static %}

    {% block title %}
        Ząbek - Nowe zamówienie
    {% endblock %}

    {% block header %}
        <h1>Sklep - Nowe zamówienie: </h1>
    {% endblock %}

{% block content %}
<div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
            <form class="form-horizontal" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <fieldset>
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"></span>
                            <div class="col-md-8">
                                Kupujący: {{ form.purchaser }} {{ form.purchaser.errors }}
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"></span>
                            <div class="col-md-8">
                                Miejsce odbioru: {{ form.office }} {{ form.office.errors }}
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"></span> 
                            <div class="col-md-6">
                                Produkt 1: {{ form.product_1 }} {{ form.product_1.errors }}
                            </div>
                            <div class="col-md-2">
                                Ilość: {{ form.quantity_1 }} {{ form.quantity_1.errors }}
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"></span>
                            <div class="col-md-6">
                                Produkt 2: {{ form.product_2 }} {{ form.product_2.errors }}
                            </div>
                            <div class="col-md-2">
                                Ilość: {{ form.quantity_2 }} {{ form.quantity_2.errors }}
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"></span> 
                            <div class="col-md-6">
                                Produkt 3: {{ form.product_3 }} {{ form.product_3.errors }}
                            </div>
                            <div class="col-md-2">
                                Ilość: {{ form.quantity_3 }} {{ form.quantity_3.errors }}
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"></span> 
                            <div class="col-md-6">
                                Produkt 4: {{ form.product_4 }} {{ form.product_4.errors }}
                            </div>
                            <div class="col-md-2">
                                Ilość: {{ form.quantity_4 }} {{ form.quantity_4.errors }}
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"></span> 
                            <div class="col-md-6">
                                Produkt 5: {{ form.product_5 }} {{ form.product_5.errors }}
                            </div>
                            <div class="col-md-2">
                                Ilość: {{ form.quantity_5 }} {{ form.quantity_5.errors }}
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"></span> 
                            <div class="col-md-8">
                                Uwagi: {{ form.additional_info }} {{ form.additional_info.errors }}
                            </div>
                        </div>
                         <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-primary btn-lg">Kup</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

tooth/shop/templates/shop/product_category.html
{% extends "base.html" %}

    {% load django_markdown %}
    {% load  static %}

    {% block title %}
        Ząbek - Sklep - Kategoria
    {% endblock %}

    {% block header %}
        {% if object_list %}
            {% for object in object_list %}
                {% if forloop.counter == 1 %}
                    <h1>Kategoria: '{{ object.category }}'</h1>
                {% endif %}
            {% endfor %}
             {% else %}
            {% endif %}
    {% endblock %}

{% block content %}
        
	    <div class="container">
            {% if object_list %}
            {% for object in object_list %}
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="{{ object.get_absolute_url }}">
                    <img class="img-responsive" src="http://placehold.it/400x300" alt="">
                    <div class="product_info">
                        <div style="text-align: center; white-space: nowrap;
                        overflow: hidden; text-overflow: ellipsis; max-width: 300px;" class="product_title">{{ object.name }}</div>
                        <div style="text-align: center;" class="product_price">jedynie: {{ object.price_in_PLN }} PLN</div>
                    </div>
                </a>
            </div>
            {% endfor %}
            {% endif %}
    </div>
	        

{% endblock %}

tooth/shop/templates/shop/product_detail.html
{% extends "base.html" %}

    {% load django_markdown %}
    {% load  static %}

    {% block title %}
        Ząbek - Sklep - {{ object.name }}
    {% endblock %}

    {% block header %}
        <h1>Sklep - {{ object.name }} </h1>
    {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                {% if object.photo %}
                    <img src="{{ object.photo.url }}"/>
                {% else %}
                    <img class="img-responsive" src="http://placehold.it/400x300" alt="">
                {% endif %}
            </div>
            <div class="col-md-8">
            <p><a href="{% url 'shop:new_purchase' %}">Przejdz do formularza zakupu!</a></p>
                <h3>{{ object.name }}</h3>
                <h3>Producent: </h3>
                <p> {{ object.manufacturer }} </p>
                <h3>Opis: </h3>
                <p> {{ object.description }} </p>
                <h3>Cena: </h3>
                <p>{{ object.price_in_PLN }} PLN</p>

                {% if object.category %}
                <div class="category">
                  <span>Category: </span>
                <a href="{{ object.category.get_absolute_url }}"><span class="label label-primary">{{ object.category.name }}</span></a>
                </div>
                {% endif %}
                {% if object.tags %}
                <div class="tags">
                  <span>Tagged under: </span>
                {% for tag in object.tags.all %}
                <a href="{{ tag.get_absolute_url }}"><span class="label label-success">{{ tag.name }}</span></a>
                {% endfor %}
                </div>
                {% endif %}
                <div class="social">
                    {% with object.get_absolute_url as page_url %}
                    {% with object.title as title %}
                    {% include 'share.html' %}
                    {% endwith %}
                    {% endwith %}</div>
               <div class="comments">
            <h3>Komentarze:</h3>
                <div class="fb-comments" data-href="http://localhost:800{{ object.get_absolute_url }}" data-width="470" data-num-posts="10"></div>
            </div>
            </div>
            
        </div>
    </div>
	        

{% endblock %}

tooth/shop/templates/shop/product_tag.html
{% extends "base.html" %}

    {% load django_markdown %}
    {% load  static %}

    {% block title %}
        Ząbek - edycja gabinetu
    {% endblock %}

    {% block header %}
        <h1>Sklep - Tag: </h1>
    {% endblock %}

{% block content %}
        
                {{ object }}
            

{% endblock %}

tooth/shop/templates/shop/products_list.html
{% extends "base.html" %}

    {% load django_markdown %}
    {% load  static %}

    {% block title %}
        Ząbek - edycja gabinetu
    {% endblock %}

    {% block header %}
        <h1>Produkty w naszym sklepie:</h1>
    {% endblock %}

{% block content %}
    <h3><a href="{% url 'shop:new_purchase' %}">Przejdz do formularza zakupu!</a></h3>
    <div class="container">
            {% if object_list %}
            {% for object in object_list %}
            {% if object.retail %}
            <div class="col-md-4 thumb">
                <a class="thumbnail" href="{{ object.get_absolute_url }}">
                {% if object.photo %}
                    <img src="{{ object.photo.url }}"/>
                {% else %}
                    <img class="img-responsive" src="http://placehold.it/400x300" alt="">
                {% endif %}
                    <div class="product_info">
                        <div style="text-align: center; white-space: nowrap;
                        overflow: hidden; text-overflow: ellipsis;" class="product_title">{{ object.name }}</div>
                        <div style="text-align: center;" class="product_price">jedynie: {{ object.price_in_PLN }} PLN</div>
                    </div>
                </a>
            </div>
            {% endif %}
            {% endfor %}
        {% else %}
            <p>Nie znaleziono produktów...</p>
        {% endif %}
    </div>
        <div>
        <ul class="pager">
            {% if page_obj.has_previous %}
                <li class="previous"><a href="?page={{ page_obj.previous_page_number }}">Poprzednia strona</a></li>
            {% endif %}
            {% if page_obj.has_next %}
                <li class="next"><a href="?page={{ page_obj.next_page_number }}">Następna strona</a></li>
            {% endif %}
        </ul>
        </div>
    </div>

{% endblock %}

tooth/shop/templates/shop/purchase_detail.html
{% extends "base.html" %}

    {% load django_markdown %}
    {% load  static %}

    {% block title %}
        Ząbek - szczegóły zamówienia
    {% endblock %}

    {% block header %}
        <h1>Szczegóły zamówienia</h1>
    {% endblock %}

    {% block content %}
    {% if request.user == object.office.user or request.user == object.purchaser %}
    <div class="row">
    <h4>Data: {{object.date}}</h4>
    <h4>Cena: {{object.total_price}}</h4>
    <h4>Status: {{object.status_verbose}}</h4>
    <h4>Kod transakcji do przelewu: {{object.purchase_id}}</h4>
    <h4>Produkty:</h4>
    {% if object.product_1 %}
    <p>{{object.product_1.name}} (cena: {{object.product_1.price_in_PLN}} PLN) X {{object.quantity_1}} szt.<p>
    {% endif %}
    {% if object.product_2 %}
    <p>{{object.product_2.name}} (cena: {{object.product_2.price_in_PLN}} PLN) X {{object.quantity_2}} szt.<p>
    {% endif %}
    {% if object.product_3 %}
    <p>{{object.product_3.name}} (cena: {{object.product_3.price_in_PLN}} PLN) X {{object.quantity_3}} szt.<p>
    {% endif %}
    {% if object.product_4 %}
    <p>{{object.product_4.name}} (cena: {{object.product_4.price_in_PLN}} PLN) X {{object.quantity_4}} szt.<p>
    {% endif %}
    {% if object.product_5 %}
    <p>{{object.product_5.name}} (cena: {{object.product_5.price_in_PLN}} PLN) X {{object.quantity_5}} szt.<p>
    {% endif %}
    <h4>Dodatkowe uwagi: {{object.additional_info}}</h4>
    </div>
    {% endif %}
    {% endblock %}

tooth/shop/templates/shop/purchase_list.html
{% extends "base.html" %}

    {% load django_markdown %}
    {% load  static %}

    {% block title %}
        Ząbek - twoje zamówienia
    {% endblock %}

    {% block header %}
    {% if user.groups.all.0.name == 'Patients' %}        
    <h1>Twoje zamówienia</h1>
    {% else %}
    <h1>Zamówienia klientów z miejscem odbioru w Twoim gabinecie:</h1>
    {% endif %}
    {% endblock %}

    {% block content %}
        {% if object_list %}
        {% for purchase in object_list %}
            {% if forloop.counter == 1 %}
            {% if user.id == purchase.purchaser.id %}
            <h3>Numer bankowy do przelewu: <b class="info">55 1010 1234 1232 5050 0000</b></h3>
            <h3>Adres: <b>"Ząbek Sp. z o.o, 00-000 Miasto, ul. Krzywa 1/2"</b></h3>
            <h3>Na wszelkie pytania postara się odpowiedzieć nasze call center w godzinach 10.00-18.00 pod numerem telefonu: <b>+48 800 345 123</b></h3>
            <BR>&nbsp;<BR>
            {% endif %}
            {% endif %}
        {% endfor %}
            <table class="table table-striped">
            <thead>
                <tr>
                    <th>Data zamówienia:</th>
                    <th>Tytuł przelewu:</th>
                    <th>Cena:</th>
                    <th>Status:</th>
                    <th>Miejsce odbioru:</th>
                    <th>Więcej informacji</th>
                </tr>
            </thead>
            <tbody>
            {% for purchase in object_list %}
            <tr>
                <td>
                    {{ purchase.date }}
                </td>
                <td>
                    {{ purchase.purchase_id }}
                </td>
                <td>
                    {{ purchase.total_price }} PLN
                </td>
                <td>
                    {{ purchase.status_verbose }}
                </td>
                <td>
                    <a href="{{purchase.office.get_absolute_url}}">{{ purchase.office.name }}
                </td>
                <td>
                    <a id="more_info" href="{{ purchase.get_absolute_url }}">więcej informacji...</a>
                </td>
                    {% if user == purchase.office.user %}
                        <td><a id="more_info" href="{{ purchase.get_edit_url }}">edytuj...</a></td>
                    {% endif %}
            </div>
            </tr>
            {% endfor %}
            </tbody>
            </table>
        {% else %}
            <p>Nie znaleziono zakupów!</p>
            {% if user.is_authenticated %}
            {% if user.groups.all.0.name == 'Patients' %}
            <p><a href="{% url 'shop:shop_index' %}">Może odwiedzisz nasz sklep?</a></p>
            {% endif %}
            {% endif %}
        {% endif %}

        <ul class="pager">
            {% if page_obj.has_previous %}
                <li class="previous"><a href="?page={{ page_obj.previous_page_number }}">Poprzednia strona</a></li>
            {% endif %}
            {% if page_obj.has_next %}
                <li class="next"><a href="?page={{ page_obj.next_page_number }}">Następna strona</a></li>
            {% endif %}
        </ul>

    {% endblock %}

tooth/shop/templates/shop/purchase_status_edit.html
{% extends "base.html" %}

    {% load django_markdown %}
    {% load  static %}

    {% block title %}
        Ząbek - edycja statusu zamówienia
    {% endblock %}

    {% block header %}
        <h1>Edycja statusu zamówienia:</h1>
    {% endblock %}

    {% block content %}
    {% for purchase in purchase_list %}
    	<p>Data zakupu: {{purchase.date}}<p>
    	<p>Klient: {{purchase.purchaser.patient_set.all.0.surname}} {{purchase.purchaser.patient_set.all.0.name}}, PESEL: {{purchase.purchaser.patient_set.all.0.pesel}}</p>
    {% endfor %}
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
                <form class="form-horizontal" method="POST" enctype="multipart/form-data">{% csrf_token %}
                        <div class="form-group">
                        <br>&nbsp;</br>
                            <span class="col-md-1 col-md-offset-2 text-center"></span> 
                            <div class="col-md-8">
                                {{ form.status }} {{ form.status.errors }}
                            </div>
                        </div>
                         <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-primary btn-lg">Zapisz</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}