tooth/blog/urls.py
from django.conf.urls import *
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.views.generic import ListView, DetailView
from . import views, feed, models

info_dict = {
    'queryset' : models.Post.objects.published(),
    'date_field' : 'pub_date',
}

urlpatterns = [
	url(r'^/(?P<pub_date__year>\d{4})/(?P<pub_date__month>\d{1,2})/(?P<slug>[a-zA-Z0-9-]+)/?',
		views.PostDetail.as_view(), name="post_detail"),
	url(r'^/new/', views.post_new, name='post_new'),
	url(r'^/category/(?P<slug>[a-zA-Z0-9-]+)/?$', views.CategoryView.as_view(), name="category"),
    url(r'^/tag/(?P<slug>[a-zA-Z0-9-]+)/?$', views.TagView.as_view(), name="tag"),
	url(r'^', views.BlogIndex.as_view(), name="blog"),
	]

tooth/email_marketing/urls.py
from django.conf.urls import *
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET, require_POST
from . import views

urlpatterns = [
	url(r'^/emails_list/$', views.MarketingEmailList.as_view(), name='emails_list'),
	url(r'^/emails_detail/(?P<pk>[0-9]+)/?', views.MarketingEmailDetail.as_view(), name='email_detail'),
	url(r'^$', views.NewMarketingEmail.as_view(), name='new_marketing_email'),
	]

tooth/main_page/urls.py
from django.conf.urls import *
from . import views


urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^about', views.AboutView.as_view(), name='about'),
	url(r'^login', views.login_user, name='login_user'),
	url(r'^logout', views.logout_user, name='logout_user'),
	url(r'^account', views.OfficeIndexView.as_view(), name="office_account"),
	url(r'^contact', views.contact, name='contact'),
    url(r'^thanks', views.thanks, name='thanks'),
    url(r'^forbidden', views.AccessForbiddenView.as_view(), name="forbidden"),
	url(r'^password_reset', views.password_reset, name="password_reset"),

	#dentist
	url(r'^dentists', views.DentistsListView.as_view(), name='dentists'),
	url(r'^dentist/update/(?P<slug>[a-zA-Z0-9-]+)/?', views.DentistUpdateView.as_view(), name="dentist_update"),
	url(r'^dentist/(?P<slug>[a-zA-Z0-9-]+)/?', views.DentistDetailView.as_view(), name='dentist'),
	url(r'^new_dentist', views.DentistCreateView.as_view(), name="new_dentist"),

	# office
	url(r'^offices', views.OfficesListView.as_view(), name='offices'),
	url(r'^office/update/(?P<slug>[a-zA-Z0-9-]+)/?', views.OfficeUpdateView.as_view(), name="office_update"),
	url(r'^office/(?P<slug>[a-zA-Z0-9-]+)/?', views.OfficeDetailView.as_view(), name='office'),

	# patients
	url(r'^patients', views.PatientsListView.as_view(), name='patients'),
	url(r'^patient/event/(?P<slug>[a-zA-Z0-9-]+)/?', views.EventDetailView.as_view(), name='event_detail'),
	url(r'^patient/update/(?P<slug>[a-zA-Z0-9-]+)/?', views.PatientUpdateView.as_view(), name="patient_update"),
	url(r'^patient/(?P<slug>[a-zA-Z0-9-]+)/?', views.PatientDetailView.as_view(), name='patient'),
	url(r'^new_patient', views.PatientCreateView.as_view(), name="new_patient"),
	url(r'^change_password', views.password_change, name="change_password"),
	url(r'^patient_zone/patient_info', views.UserPersonalDataView.as_view(), name="patient_info"),
	url(r'^patient_zone/patient_history', views.UserEventsView.as_view(), name="patient_history"),
	url(r'^patient_zone/patient_appointements', views.PatientAppointmentsView.as_view(), name="patient_appointements"),
	url(r'^patient_zone/appointment_signup/(?P<pk>[0-9]+)/$', views.UserAppointementSignUpView.as_view(), name="patient_signup_appointment"),
	url(r'^patient_zone/appointment_cancel/(?P<pk>[0-9]+)/$', views.PatientAppointmentsCancelView.as_view(), name="patient_cancel_appointments"),
	url(r'^patient_zone', views.patient_index, name='patient_index'),

	# searches
    url(r'^search_dentist', views.search_dentist, name='search_dentist'),
    url(r'^search_patient', views.search_patient, name='search_patient'),
    url(r'^search_office', views.search_office, name='search_office'),

    #schedules
    url(r'^schedule/list/$', views.SchedulesListView.as_view(), name="schedules_list"),
    url(r'^new_schedule', views.ScheduleCreateView.as_view(), name="schedule_create"),
    url(r'^schedule/day/(?P<pk>[0-9]+)/$', views.ScheduleDetailView.as_view(), name="schedule_detail"),
    url(r'^schedule/day_edit/(?P<pk>[0-9]+)/$', views.ScheduleUpdateView.as_view(), name="schedule_edit"),
    url(r'^schedule/instruction/$', views.ScheduleInstructionView.as_view(), name="schedule_instruction"),

    #events
    url(r'^event_create', views.EventCreateView.as_view(), name='event_create')

]

tooth/shop/urls.py
from django.conf.urls import *
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET, require_POST
from . import views, models

urlpatterns = [
	url(r'^/category/(?P<slug>[a-zA-Z0-9-]+)/?$', views.CategoryView.as_view(), name="shop_category"),
    url(r'^/tag/(?P<slug>[a-zA-Z0-9-]+)/?$', views.TagView.as_view(), name="shop_tag"),
	url(r'^/product/(?P<slug>[a-zA-Z0-9-]+)/?$', views.ProductDetailView.as_view(), name='shop_detail'),
	url(r'^/new_purchase/$', views.PurchaseFormView.as_view(), name='new_purchase'),
	url(r'^/purchase_list/$', views.PurchaseListView.as_view(), name='purchase_list'),
	url(r'^/purchase/(?P<pk>[0-9]+)/?', views.PurchaseDetailView.as_view(), name='purchase_details'),
	url(r'^/office/purchase_list/$', views.PurchaseOfficeListView.as_view(), name="office_purchase_list"),
	url(r'^/office/purchase/update/(?P<pk>[0-9]+)/?', views.PurchaseStatusUpdate.as_view(), name='office_purchase_status_update'),
	url(r'^$', views.ShopIndexView.as_view(), name='shop_index'),
	]

tooth/tooth/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from main_page import urls
from shop import urls
from blog import urls


urlpatterns = [
    url(r'^admin', include(admin.site.urls)),
    url('^markdown/', include( 'django_markdown.urls')),
    url(r'^blog', include('blog.urls', namespace='blog')),
    url(r'^shop', include('shop.urls', namespace='shop')),
    url(r'^email_marketing', include('email_marketing.urls', namespace='email_marketing')),
    url(r'^', include('main_page.urls', namespace="main_page")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.conf.urls import handler400, handler403, handler404, handler500

handler400 = 'main_page.views.handler400'
handler403 = 'main_page.views.handler403'
handler404 = 'main_page.views.handler404'
handler500 = 'main_page.views.handler500'

tooth/main_page/views.py
from django.views import generic
from django.shortcuts import render_to_response, render, redirect
from django.template import RequestContext
from django.views.generic import TemplateView
from .forms import ContactForm
from django.utils.text import slugify
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator, EmptyPage
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.contrib import messages
from django.core.urlresolvers import reverse
from braces.views import GroupRequiredMixin, LoginRequiredMixin
from . import models, forms
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.core.mail import send_mail


#office
class EventCreateView(CreateView):
    model = models.Event
    template_name = 'office/new_event.html'
    form_class = forms.EventCreateForm

    def get_form_kwargs(self):
        kwargs = super(EventCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.groups.filter(name='Offices').count() == 1, login_url='/forbidden'))
    def dispatch(self, *args, **kwargs):
        return super(EventCreateView, self).dispatch(*args, **kwargs)

#login_required
class EventDetailView(generic.DetailView):
    model = models.Event
    template_name = 'patient/event_detail.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(EventDetailView, self).dispatch(*args, **kwargs)

#patient
class UserEventsView(generic.ListView):
    model = models.Patient
    template_name = "patient/patient_history.html"
    paginate_by = 10

    def get_queryset(self):
        queryset = super(UserEventsView, self).get_queryset().filter(user=self.request.user)
        return queryset

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.groups.filter(name='Patients').count() == 1, login_url='/forbidden'))
    def dispatch(self, *args, **kwargs):
        return super(UserEventsView, self).dispatch(*args, **kwargs)

#patients
class UserPersonalDataView(generic.ListView):
    queryset = models.Patient.objects.all()
    model = models.Patient
    template_name = "patient/patient_info.html"

    def get_queryset(self):
        queryset = super(UserPersonalDataView, self).get_queryset().filter(user=self.request.user)
        return queryset

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.groups.filter(name='Patients').count() == 1, login_url='/forbidden'))
    def dispatch(self, *args, **kwargs):
        return super(UserPersonalDataView, self).dispatch(*args, **kwargs)

#patient
class UserAppointementSignUpView(UpdateView):
    model = models.DentistDay
    template_name = "patient/patient_signup_appointment.html"
    form_class = forms.UserAppointementSignUpForm

    def get_success_url(self):
        return reverse('main_page:patient_appointements')

    def get_form_kwargs(self):
        kwargs = super(UserAppointementSignUpView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['request'] = self.request
        return kwargs

    def get_context_data(self, **kwargs):
        dday_pk = self.get_object().pk
        context = super(UserAppointementSignUpView, self).get_context_data(**kwargs)
        context['dday'] = models.DentistDay.objects.filter(pk=dday_pk)
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UserAppointementSignUpView, self).dispatch(*args, **kwargs)

#patient
class PatientInfoView(generic.DetailView):
    model = models.Patient
    template_name = 'patient/patient_info.html'

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.groups.filter(name='Patients').count() == 1, login_url='/forbidden'))
    def dispatch(self, *args, **kwargs):
        return super(PatientInfoView, self).dispatch(*args, **kwargs)

#patient
class PatientHistoryView(generic.DetailView):
    model = models.Patient
    template_name = 'patient/patient_history.html'

    def get_context_data(self, **kwargs):
        patient = self.get_object().pk
        context = super(PatientHistoryView, self).get_context_data(**kwargs)
        context['events'] = models.Event.objects.filter(subject=patient).order_by('date')
        return context

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.groups.filter(name='Patients').count() == 1, login_url='/forbidden'))
    def dispatch(self, *args, **kwargs):
        return super(PatientHistoryView, self).dispatch(*args, **kwargs)

#patient
class PatientAppointmentsCancelView(generic.UpdateView):
    model = models.DentistDay
    template_name = "patient/patient_cancel_appointments.html"
    form_class = forms.UserAppointmentCancelForm

    def get_success_url(self):
        return reverse('main_page:patient_appointements')

    def get_form_kwargs(self):
        kwargs = super(PatientAppointmentsCancelView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['request'] = self.request
        return kwargs

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.groups.filter(name='Patients').count() == 1, login_url='/forbidden'))
    def dispatch(self, *args, **kwargs):
        return super(PatientAppointmentsCancelView, self).dispatch(*args, **kwargs)

#patient
class PatientAppointmentsView(generic.ListView):
    queryset = models.DentistDay.objects.all().order_by('date')
    template_name = "patient/patient_appointements.html"
    paginate_by = 10

    def get_queryset(self):
        user_id = self.request.user.id
        object_list = super(PatientAppointmentsView, self).get_queryset()
        return object_list.filter(Q(slot10_11=user_id) | Q(slot11_12=user_id) | Q(slot12_13=user_id) |
            Q(slot13_14=user_id) | Q(slot14_15=user_id) | Q(slot15_16=user_id) | Q(slot16_17=user_id) |
            Q(slot17_18=user_id) | Q(slot18_19=user_id) | Q(slot19_20=user_id)).order_by('date')

    def get_form_kwargs(self):
        kwargs = super(PatientAppointmentsView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.groups.filter(name='Patients').count() == 1, login_url='/forbidden'))
    def dispatch(self, *args, **kwargs):
        return super(PatientAppointmentsView, self).dispatch(*args, **kwargs)

#open
class PatientCreateView(CreateView):
    model = models.Patient
    template_name = 'patient/new_patient.html'
    form_class = forms.NewPatientForm

    def get_success_url(self):
        if self.request.user.groups.all() and self.request.user.groups.all()[0].name == "Offices":
            return reverse('main_page:patients')
        else:
            return reverse('main_page:login_user')

    def form_valid(self, form):
        if self.request.user.groups.all() and self.request.user.groups.all()[0].name == "Offices":
            messages.add_message(self.request, messages.INFO, 'Konto zostało utworzone. Na skrzynkę mailową pacjenta została wysłana wiadomość z loginem i hasłem')
        else:
            messages.add_message(self.request, messages.INFO, 'Konto zostało utworzone. Na skrzynkę mailową została wysłana wiadomość z loginem i hasłem')
        return super(PatientCreateView, self).form_valid(form)

#office
class SchedulesListView(generic.ListView):
    queryset = models.DentistDay.objects.all()
    template_name = "office/dentist_schedules_list.html"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        user_id = self.request.user.id
        context = super(SchedulesListView, self).get_context_data(**kwargs)
        context['dentists'] = models.Dentist.objects.filter(office__user_id=user_id)
        return context

    def get_queryset(self):
        user_id = self.request.user.id
        object_list = super(SchedulesListView, self).get_queryset()
        return object_list.filter(office__user_id=user_id).order_by('date')

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.groups.filter(name='Offices').count() == 1, login_url='/forbidden'))
    def dispatch(self, *args, **kwargs):
        return super(SchedulesListView, self).dispatch(*args, **kwargs)

#office
class ScheduleCreateView(CreateView):
    model = models.DentistDay
    template_name = 'office/new_dentist_schedule.html'
    form_class = forms.NewScheduledDay

    def get_form_kwargs(self):
        kwargs = super(ScheduleCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.groups.filter(name='Offices').count() == 1, login_url='/forbidden'))
    def dispatch(self, *args, **kwargs):
        return super(ScheduleCreateView, self).dispatch(*args, **kwargs)

#office
class ScheduleUpdateView(UpdateView):
    model = models.DentistDay
    template_name = 'office/new_dentist_schedule.html'
    form_class = forms.UserAppointementEditForm

    def get_form_kwargs(self):
        kwargs = super(ScheduleUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.groups.filter(name='Offices').count() == 1, login_url='/forbidden'))

tooth/main_page/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="alternate" type="application/rss+xml" title="Blog posts" href="/feed" >

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'ui/jquery-ui.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <script src="{% static 'js/jquery-1.11.3.js' %}"></script>
        <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
        <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
        <script src="{% static 'ui/jquery-ui.js' %}"</script>
        <script src="{% static 'js/all.min.js' %}"></script>

        <script src="http://skryptcookies.pl/cookie.js"></script>

        {% block script %}{% endblock %}

    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

        <script>
        $(document).ready(function() {
            $('.datepicker').datepicker({dateFormat: 'dd.mm.yy'});
        });
        </script>

        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a style="color: #2040FF;" class="navbar-brand" href="{% url 'main_page:index' %}"><strong>Ząbek</strong></a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                         <li><a href="{% url 'main_page:schedule_instruction' %}">Jak się zapisać?</a></li>
                        <li><a href="{% url 'main_page:offices' %}">Nasze Gabinety</a></li>
                        <li><a href="{% url 'main_page:dentists' %}">Nasi Dentyści</a></li>
                        <li><a href="{% url 'blog:blog' %}">Blog</a></li>
                        <li><a href="{% url 'shop:shop_index' %}">e-Sklep</a></li>
                        <li><a href="{% url 'main_page:contact' %}">Kontakt</a></li>
                        <li><a href="{% url 'main_page:about' %}">O nas</a></li>
                        {% if user.is_authenticated %}
                        {% if user.groups.all.0.name == 'Offices' %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Twój Gabinet <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'main_page:office_account' %}">Strona gabinetu</a></li>
                                <li><a href="{% url 'main_page:schedules_list' %}">Grafik</a></li>
                                <li><a href="{% url 'main_page:patients' %}">Pacjenci</a></li>
                                <li><a href="{% url 'main_page:new_patient' %}">Dodaj pacjenta</a></li>
                                <li><a href="{% url 'main_page:new_dentist' %}">Dodaj dentystę</a></li>
                                <li><a href="{% url 'main_page:schedule_create' %}">Dodaj grafik</a></li>
                                <li><a href="{% url 'main_page:event_create' %}">Dodaj wydarzenie</a></li>
                                <li><a href="{% url 'shop:office_purchase_list' %}">Zamówienia do wydania klientom</a></li>
                                <li role="separator" class="divider"></li>
                                <li class="dropdown-header">Inne:</li>
                                <li><a href="{% url 'blog:post_new' %}">Wyślij post na bloga</a></li>
                                <li><a href="{% url 'email_marketing:new_marketing_email' %}">Email marketing</a></li>
                                <li><a href="{% url 'email_marketing:emails_list' %}">Lista wysłanych emaili</a></li>
                                <li><a href="{% url 'main_page:change_password' %}">Zmień hasło</a></li>
                            </ul>
                        </li>
                        {% endif %}
                        {% if user.groups.all.0.name == 'Patients' %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Strefa Użytkownika<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'main_page:patient_index' %}">Twoja strona</a></li>
                                <li><a href="{% url 'main_page:patient_appointements' %}">Twoje wizyty</a></li>
                                <li><a href="{% url 'main_page:patient_info' %}">Twoje dane</a></li>
                                <li><a href="{% url 'main_page:patient_history' %}">Twoja historia leczenia</a></li>
                                <li><a href="{% url 'shop:purchase_list' %}">Twoje zakupy</a></li>
                                <li role="separator" class="divider"></li>
                                <li class="dropdown-header">Inne:</li>
                                <li><a href="{% url 'main_page:change_password' %}">Zmień hasło</a></li>
                            </ul>
                        </li>
                        {% endif %}
                        {% endif %}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if not user.is_authenticated %}
                        <li style="text-align: right;"><a href="{% url 'main_page:new_patient' %}">Zarejestruj się</a></li>
                        <li style="text-align: right;"><a href="{% url 'main_page:login_user' %}">Zaloguj</a></li>
                        {% endif %}
                        {% if user.is_authenticated %}
                        <li id="log_out"><a href="{% url 'main_page:logout_user' %}">Wyloguj</a></li>
                        {% endif %}
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <div class="page-header">
                {% block header %}{% endblock %}
            </div>
                {% block content %}{% endblock %}
        </div>
        <br>&nbsp;</br>
        <footer class="footer">
            <div class="container">
                <p class="text-muted">Copyright &copy; {% now "Y" %} Ząbek Sp. z o.o, 00-000 Miasto, ul. Krzywa 1/2, NIP: 000-00-00-000, KRS 0000000000, Regon: 0000000000, Kapitał zakładowy 1 000 000 zł
            </div>
        </footer>

        <script src="{% static 'js/bootstrap.min.js' %}"></script>

	</body>
</html>

tooth/main_page/templates/forbidden.html
{% extends "base.html" %}

{% load django_markdown %}
{% load staticfiles %}
{% load  static %}

	{% block title %}
		Ząbek - Dostęp zabroniony
	{% endblock %}

	{% block header %}
        <h1 class="info">Dostęp do tego zasobu jest zastrzeżony!!!</h1>
    {% endblock %}

    {% block content %}
    	<h3>{% if not user.is_authenticated %}
    	<a href="{% url 'main_page:login_user' %}">Zaloguj się</a> lub <a href="{% url 'main_page:new_patient' %}">zarejestruj</a> lub
    	{% endif %}
    	<a href="{% url 'main_page:index' %}">wróć do strony głównej</a></h3>
<div class="row">
		<div class="col-md-4">
		
	</div>
</div>
    {% endblock %}

tooth/main_page/templates/index.html
{% extends "base.html" %}

{% load django_markdown %}
{% load staticfiles %}
{% load  static %}

	{% block title %}
		Ząbek - strona główna
	{% endblock %}

	{% block header %}
        <h1>Sieć gabinetów dentystycznych "Ząbek"</h1>
    {% endblock %}

    {% block content %}
<div class="row">
		<div class="col-md-4">
			<img src="{% static 'img/dentistLogo.jpg' %}">
		</div>
		<div class="col-md-8">
			<h2>
				Witamy na stronie sieci gabinetów stomatologicznych "Ząbek"
			</h2>
			<h3><p class="description">
				Jesteśmy siecią gabinetów stomatologicznych działających na terenie całej Polski. Oferujemy Państwu opiekę stomatologiczną na najwyższym, światowym poziomie. Kreowanie pięknych i zdrowych uśmiechów to nasz najwyższy priorytet.
			</p>
			<p>
			<a class="btn" href="{% url 'main_page:about' %}">Więcej...</a>
			</p></h3>
		</div>
	</div>
</div>
    {% endblock %}

tooth/main_page/templates/login.html
{% extends 'base.html' %}

    {% block title %}
        Ząbek - logowanie do gabinetu
    {% endblock %}

    {% block header %}
        <h1>Logowanie:</h1>
    {% endblock %}

{% block content %}
<h3><a href="{% url 'main_page:new_patient' %}">Załóż konto</a></h3>
<h3><a href="{% url 'main_page:password_reset' %}">Zresetuj hasło</a></h3>
	<form style="max-width: 330px; padding: 15px; margin: 0 auto;" class="form-signin" id="login_form" method="POST" action="/login/">
	    {% csrf_token %}
	    	{% if messages %}
	    		{% for message in messages %}
	    		{% if forloop.counter == 1 %}
	    		<p style="text-align: center;" class="important"><i class="glyphicon glyphicon-warning-sign info">&nbsp;</i>{{ message }}</p>
	    		{% endif %}
	    		{% endfor %}
	    	{% endif %}
	        <p style="text-align: center;"><i class="glyphicon glyphicon-user bigicon"></i></p>
	        <input class="form-control" type="text" placeholder="Nazwa użytkownika" name="username" value="" size="50" required="" autofocus=""/>
	        <br />
	        <p style="text-align: center;"><i class="glyphicon glyphicon-lock bigicon"></i></p>
	        <input class="form-control" type="password" placeholder="Hasło" name="password" value="" size="50" required="" autofocus=""/>
	        <br />

	    <button class="btn btn-lg btn-primary btn-block" type="submit" value="submit">Zaloguj</button>
	</form>
{% endblock %}